"""One-command post-5year validation pipeline.

Steps:
1) Audit race_history after the JV-Link backfill.
2) Rebuild leakage-safe features from the enlarged history.
3) Retrain the existing LightGBM winner/place models with chronological holdout.
4) Evaluate race-level ranking accuracy on the untouched holdout period.

The historical race rows are read-only in this script. Only feature_history,
model files and an output report are regenerated by the existing project code.
"""
from __future__ import annotations

import json
import sqlite3
import sys
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.database import DEFAULT_DATABASE_PATH
from scripts.feature_engine import FeatureEngineeringEngine
from scripts.train_model import LightGBMTrainingEngine, load_model_bundle, transform_for_prediction

JST = timezone(timedelta(hours=9))
OUT_DIR = ROOT / "outputs" / "baseline"
JSON_OUT = OUT_DIR / "POST_5YEAR_VALIDATION.json"
TXT_OUT = OUT_DIR / "POST_5YEAR_VALIDATION.txt"


def now() -> str:
    return datetime.now(JST).isoformat(timespec="seconds")


def audit_history() -> dict:
    with sqlite3.connect(DEFAULT_DATABASE_PATH) as con:
        min_date, max_date, rows, races = con.execute(
            "SELECT MIN(race_date), MAX(race_date), COUNT(*), COUNT(DISTINCT race_key) FROM race_history"
        ).fetchone()
        duplicate_keys = con.execute(
            """
            SELECT COUNT(*) FROM (
              SELECT race_key, horse_no, COUNT(*) c
              FROM race_history
              GROUP BY race_key, horse_no
              HAVING c > 1
            )
            """
        ).fetchone()[0]
        null_finish = con.execute(
            "SELECT COUNT(*) FROM race_history WHERE finish_position IS NULL"
        ).fetchone()[0]
        yearly = {
            str(year): {"runner_rows": int(runner_rows), "race_count": int(race_count)}
            for year, runner_rows, race_count in con.execute(
                """
                SELECT SUBSTR(race_date,1,4) y, COUNT(*), COUNT(DISTINCT race_key)
                FROM race_history
                GROUP BY y ORDER BY y
                """
            )
        }
    return {
        "min_date": min_date,
        "max_date": max_date,
        "runner_rows": int(rows),
        "race_count": int(races),
        "duplicate_race_horse_keys": int(duplicate_keys),
        "null_finish_position": int(null_finish),
        "yearly": yearly,
    }


def load_validation_rows(validation_start: str):
    with sqlite3.connect(DEFAULT_DATABASE_PATH) as con:
        con.row_factory = sqlite3.Row
        return con.execute(
            """
            SELECT * FROM feature_history
            WHERE race_date >= ?
            ORDER BY race_date, race_key, horse_no
            """,
            (validation_start,),
        ).fetchall()


def race_level_metrics(validation_start: str) -> dict:
    winner = load_model_bundle(ROOT / "models" / "winner_model.pkl")
    place = load_model_bundle(ROOT / "models" / "place_model.pkl")
    rows = load_validation_rows(validation_start)
    if not rows:
        raise RuntimeError("validation rows are empty")

    win_x = transform_for_prediction(rows, winner)
    place_x = transform_for_prediction(rows, place)
    win_p = [float(x) for x in winner["booster"].predict(win_x)]
    place_p = [float(x) for x in place["booster"].predict(place_x)]

    grouped = defaultdict(list)
    for row, wp, pp in zip(rows, win_p, place_p):
        grouped[str(row["race_key"])].append((row, wp, pp))

    race_count = 0
    winner_hit = 0
    exact_12 = 0
    exact_123 = 0
    winner_in_top3 = 0
    actual_top3_captured = 0

    for race_rows in grouped.values():
        actual = sorted(race_rows, key=lambda x: int(x[0]["target_finish_position"]))
        if len(actual) < 3:
            continue
        predicted = sorted(race_rows, key=lambda x: x[1], reverse=True)
        predicted_place = sorted(race_rows, key=lambda x: x[2], reverse=True)
        race_count += 1

        actual_order = [int(x[0]["horse_no"]) for x in actual[:3]]
        pred_order = [int(x[0]["horse_no"]) for x in predicted[:3]]
        pred_place_top3 = {int(x[0]["horse_no"]) for x in predicted_place[:3]}

        winner_hit += int(pred_order[0] == actual_order[0])
        exact_12 += int(pred_order[:2] == actual_order[:2])
        exact_123 += int(pred_order[:3] == actual_order[:3])
        winner_in_top3 += int(actual_order[0] in set(pred_order[:3]))
        actual_top3_captured += int(set(actual_order) == pred_place_top3)

    if race_count == 0:
        raise RuntimeError("no evaluable races in validation holdout")

    return {
        "validation_start": validation_start,
        "race_count": race_count,
        "winner_top1_hits": winner_hit,
        "winner_top1_rate": winner_hit / race_count,
        "exact_1_2_hits": exact_12,
        "exact_1_2_rate": exact_12 / race_count,
        "exact_1_2_3_hits": exact_123,
        "exact_1_2_3_rate": exact_123 / race_count,
        "winner_in_predicted_top3_hits": winner_in_top3,
        "winner_in_predicted_top3_rate": winner_in_top3 / race_count,
        "actual_top3_set_captured_hits": actual_top3_captured,
        "actual_top3_set_captured_rate": actual_top3_captured / race_count,
    }


def write_report(report: dict) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    a = report["audit"]
    m = report["race_level_holdout"]
    lines = [
        "HorseRacingAI POST-5YEAR VALIDATION",
        f"status={report['status']}",
        f"history={a['min_date']}..{a['max_date']}",
        f"runner_rows={a['runner_rows']}",
        f"race_count={a['race_count']}",
        f"duplicate_keys={a['duplicate_race_horse_keys']}",
        f"null_finish={a['null_finish_position']}",
        f"validation_start={m['validation_start']}",
        f"validation_races={m['race_count']}",
        f"winner_top1={m['winner_top1_hits']}/{m['race_count']} ({m['winner_top1_rate']:.2%})",
        f"exact_1_2={m['exact_1_2_hits']}/{m['race_count']} ({m['exact_1_2_rate']:.2%})",
        f"exact_1_2_3={m['exact_1_2_3_hits']}/{m['race_count']} ({m['exact_1_2_3_rate']:.2%})",
        f"winner_in_top3={m['winner_in_predicted_top3_hits']}/{m['race_count']} ({m['winner_in_predicted_top3_rate']:.2%})",
        f"actual_top3_set_captured={m['actual_top3_set_captured_hits']}/{m['race_count']} ({m['actual_top3_set_captured_rate']:.2%})",
    ]
    TXT_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines), flush=True)
    print(f"JSON={JSON_OUT}", flush=True)
    print(f"TXT={TXT_OUT}", flush=True)


def main() -> int:
    report = {"status": "RUNNING", "started_at_jst": now()}
    try:
        audit = audit_history()
        report["audit"] = audit
        if audit["race_count"] < 15000 or audit["runner_rows"] < 200000:
            raise RuntimeError(f"5-year backfill appears incomplete: {audit}")
        if audit["duplicate_race_horse_keys"] != 0 or audit["null_finish_position"] != 0:
            raise RuntimeError(f"history integrity check failed: {audit}")

        feature_result = FeatureEngineeringEngine().build()
        report["features"] = {
            "source_count": int(feature_result.source_count),
            "saved_count": int(feature_result.saved_count),
        }

        reports = LightGBMTrainingEngine(validation_ratio=0.2).train_all()
        report["training"] = {
            r.model_kind: {
                "train_count": r.train_count,
                "validation_count": r.validation_count,
                "validation_start": r.validation_start,
                "accuracy": r.metrics.accuracy,
                "precision": r.metrics.precision,
                "recall": r.metrics.recall,
                "f1": r.metrics.f1,
                "roc_auc": r.metrics.roc_auc,
                "log_loss": r.metrics.log_loss,
            }
            for r in reports
        }
        validation_start = reports[0].validation_start
        report["race_level_holdout"] = race_level_metrics(validation_start)
        report["status"] = "SUCCESS"
        report["finished_at_jst"] = now()
        write_report(report)
        return 0
    except Exception as exc:
        report["status"] = "FAILED"
        report["error"] = repr(exc)
        report["finished_at_jst"] = now()
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        JSON_OUT.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps(report, ensure_ascii=False, indent=2), flush=True)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
